version: '3.8'

services:
  openswoole:
    build: .
    container_name: openswoole
    ports:
      - "9501:9501"
    volumes:
      - ./src:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_DATABASE: mysqldb
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    networks:
      - swoole_network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - swoole_network

volumes:
  mysql_data:

networks:
  swoole_network:
    driver: bridge
